[toolchain]

[features]
resolution = true
skip-lint = false

[localnet]
upload_idl_anchor = "pmetaypqG6SiB47xMigYVMAkuHDWeSDXcv3zzDrJJvA"

[devnet]
upload_idl_anchor = "pmetaypqG6SiB47xMigYVMAkuHDWeSDXcv3zzDrJJvA"

[mainnet-beta]
upload_idl_anchor = "pmetaypqG6SiB47xMigYVMAkuHDWeSDXcv3zzDrJJvA"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "6XzaKuAwqP7Nn37vwRdUqpuzNX6K8s1ADE6tHXSZG17A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
